root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ."
  bin = "tmp\\main.exe"
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  exclude_dir = ["tmp", "vendor", "testdata", "logs", "uploads"]
  exclude_regex = ["_test.go"]
  delay = 800
  stop_on_error = true
  log = "build-errors.log"

[log]
  time = true

[screen]
  clear_on_rebuild = true
